prueba/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'prueba'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('Saludo/', views.Saludo, name='Saludo'),
    path('Despedida/', views.Despedida, name='Despedida'),
    path('Adulto/<int:edad>/', views.Adulto, name='Adulto'),
    path('Simple/', views.Simple, name='Simple'),
    path('Dinamico/<str:name>/', views.Dinamico, name="Dinamico"),
    path('DinamicoForm/', views.DinamicoForm, name='DinamicoForm'),
    path('dinamico_view/', views.dinamico_view, name='dinamico_view'),
    path('Estaticos/', views.Estaticos, name="Estaticos"),
    path('Herencia/',views.Herencia, name= "Herencia"),
    path('Ejemplo/', views.Ejemplo, name= "Ejemplo"),
    path('Otra/', views.Otra, name= "Otra"),
]

forms.py
# en miapp/forms.py
from django import forms

class NombreForm(forms.Form):
    nombre = forms.CharField(label='Nombre')

prueba/views.py
from django.http import HttpResponse
from django.shortcuts import render

def Saludo(request):
    return HttpResponse("Hola Mundo")

def Despedida(request):
    return HttpResponse("Adios")

def Adulto(request,edad):
    if int(edad) >= 18:
        return HttpResponse("Es adulto")
    else:
        return HttpResponse("No es adulto")

def Simple(request):
    return render(request,'Simple.html',{})

def Dinamico(request,name):
    categories = ['code', 'desing', 'marketing', 'business']
    context = {'name' : name, 'categories':categories}
    return render(request, 'Dinamico.html', context)

def dinamico_view(request):
    nombre = request.POST.get('nombre', '')
    return render(request, 'miapp/dinamico.html', {'nombre': nombre})

def DinamicoForm(request):
    return render(request,'DinamicoForm.html',{})

def Estaticos(request):
    return render(request,'Estaticos.html',{})

def Herencia(request):
    return render(request, 'Herencia.html', {})

def Ejemplo(request):
    return render(request, 'Ejemplo.html', {})

def Otra(request):
    return render(request, 'Otra', {})

templates/Dinamico.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hola {{name}}</h1>
    <h3>Categorias</h3>
    {# Comentario de una sola linea #}

    {% comment %}
        Comentario de 
        Varias 
        Lineas    
    {% endcomment %}

    <ul>
        {% for category in categories %}
            {% if category == 'code' %}
                <li><b> {{category|upper}} </b></li>
            {% else  %}
                <li>{{category}}</li>
            {% endif %}
        {% endfor %}
        <h5>Total de categories {{categories|length}} </h5>
    </ul>
</body>

</html>

templates/DinamicoForm.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static './style.css' %}">
    <title>Document</title>
</head>
<body>
    <form method="post" action="{% url 'prueba:DinamicoForm' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Enviar</button>
    </form>

</body>

</html>

templates/Ejemplo.html
{% extends "./Layouts/Base.html" %}

templates/Estaticos.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <title>Document</title>
</head>
<body>
    <h1> Titulo </h1>
</body>
</html>

templates/Herencia.html
{% extends "./Layouts/Base.html" %}

{% block content %} 
<h1>Herencia</h1>
{% endblock  %}

templates/Layouts/Base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    {% block styles %} {% endblock  %}
    <title>{% block titulo %} {% endblock  %}</title>
</head>
<body>

    <nav>
        <a href="{% url 'Herencia' %}">Herencia</a>
        <a href="{% url 'Ejemplo' %}">Ejemplo</a>
        <a href="{% url 'Otra' %}">Otra</a>
    </nav>
    <main>
    {% block content %} {% endblock %}
    </main>

    <footer>
        Unify
    </footer>
    {% block scripts %} {% endblock  %}
</body>
</html>

templates/Otra.html
{% extends "./Layouts/Base.html" %}

templates/Simple.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <h1>Hola mundo</h1>
</body>

</html>